# Generated by Django 5.0.7 on 2024-08-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_artist_song_artist_name_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='songs', to='category_app.artist'),
        ),
    ]
