# Generated by Django 5.0.7 on 2024-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0003_alter_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.ManyToManyField(to='category_app.category'),
        ),
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(to='category_app.category'),
        ),
    ]
