# Generated by Django 5.0.7 on 2024-08-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0004_category_artist_category_song_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='category',
            field=models.ManyToManyField(related_name='category', to='category_app.category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='category_app.category'),
        ),
    ]
