# Generated by Django 5.0.7 on 2024-08-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0005_alter_artist_category_alter_song_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='category',
            field=models.ManyToManyField(related_name='artists', to='category_app.category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(related_name='songs', to='category_app.category'),
        ),
    ]
