# Generated by Django 5.0.7 on 2024-08-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0006_alter_artist_category_alter_song_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to='songs'),
        ),
    ]
