# Generated by Django 5.0 on 2024-09-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0007_alter_song_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='album_image')),
                ('release_date', models.IntegerField(null=True)),
                ('artist', models.ManyToManyField(related_name='albums', to='category_app.artist')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(related_name='songs', to='category_app.album'),
        ),
    ]
