# Generated by Django 5.0.7 on 2024-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0008_song_release_date_album_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
